import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Layout Auth",
    description: "Generated by create next app",
};

export default function AuthLayout({ children }: { children: React.ReactNode }) {
    return (
        <div className='grid grid-cols-1 md:grid-cols-2 h-screen'>

            <div className='flex flex-col items-center justify-center'>
                {children}
            </div>
            <div className="bg-[url('/login.png')] bg-no-repeat bg-cover h-full w-full hidden md:block"></div>
        </div>
    )
}


